### PR TITLE
Removed Info.plist which caused issues for the new build system.

### PR DESCRIPTION
**Pull request by sanjay-io**
This Info.plist is causing issues on Xcode 9's new build system.

### CODE REVIEW

**Comment by SanjayTCP** [comment]
@ink-spot this PR is removing a trivial file, correct me if I'm wrong though. Is it okay to merge?

**Comment by andre991** [comment]
@SanjayTCP Maybe this PR solve this issue https://github.com/ink-spot/UPCarouselFlowLayout/issues/35

**Comment by SanjayTCP** [comment]
Yup, I believe that we're forced to use the new build system in Xcode 10

**Comment by andre991** [comment]
In xcode 10 the New Build System is default, I changed to Legacy Build System and its worked.

**Comment by tiagomnh** [comment]
Added #38 that also fixes this issue by tweaking the podspec. Hopefully @ink-spot will accept one of them. 🤞

**Comment by drewpitchford** [comment]
Along with the Swift 4.2 PR, this one needs to be merged in order for the hosting app to be able to build.

**Comment by drewpitchford** [comment]
Someone with write privileges for this PR or repo has to do it I think. 

Drew

**Comment by paskalem** [comment]
Thank you very much for the advice.
Pascale

**Comment by paskalem** [comment]
Thanks again

**Comment by sanjayiothakur** [comment]
Looks like https://github.com/ink-spot/UPCarouselFlowLayout/pull/41 fixes this as well. Thanks all. Closing!

**Pull request closed without merging**
